### ISSUE TITLE
Issues with configuring JHipster with Gmail

### ISSUE THREAD

**Issue by Invizible** [RawSanj/java-mail-clients#1]
I used your tip for Gmail, and got email from google 
"Sign-in attempt prevented...Google stopped this sign-in attempt, but you should review your recently used devices:"

What can I do with this?

**Comment by RawSanj** [comment]
You need to allow your Gmail account to access less secure apps.

Login to Gmail and visit [Here](https://www.google.com/settings/security/lesssecureapps) to Turn On Access for less secure apps.

[More Info here](https://support.google.com/accounts/answer/6010255)

**Comment by Invizible** [comment]
@RawSanj Thanks

**Comment by RawSanj** [comment]
@Invizible You are welcome Sir 😃
