### ISSUE TITLE
How to send mail with attachment via this code?

### ISSUE THREAD

**Issue by khansaad** [RawSanj/java-mail-clients#2]

**Comment by RawSanj** [comment]
@khansaad check this method: https://github.com/RawSanj/java-mail-clients/blob/9cde7aad8f663c92de123b0cf36223e743b07618/src/main/java/com/rawsanj/mail/MailMessageUtils.java#L51 

You need to create `Multipart` which would be a list of `MimeBodyPart` for attachment files and a `BodyPart` for message and then call the `setContent` of Message object.

I have refactored the code and added this support in `SendEmailWithAttachments` class. Hope that helps.

**Comment by khansaad** [comment]
Thanks..got it. :+1:  :) @RawSanj
